# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba2a3df5e018b3e60d2ffff083928fa1236efb6dc6253f9f8d16eec0aa4e7568bb9ab4aec722fd149ac3c0e1c986fefc23e0e3edc03812c16d764873b12b8e88

test:
  secret_key_base: ba454813ef108369de4e96072b0b182dea9d833759b6d9a0898be105cedd124d758cef42b2c7b9e45dcc44aa0f07d40391d5047441fb6414f3e1885842bea1a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
